spring:
  application:
    name: customer
  datasource:
    url: jdbc:h2:mem:customer
#    ;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS tenant_1\;CREATE SCHEMA IF NOT EXISTS tenant_2\;create table tenant_1.customer (id bigint not null, name varchar(255), address varchar(255), family_name varchar(255), version bigint, primary key (id))\;create table tenant_2.customer (id bigint not null, name varchar(255), address varchar(255), family_name varchar(255), version bigint, primary key (id))\; create sequence tenant_1.hibernate_sequence start with 1 increment by 1\; create sequence tenant_2.hibernate_sequence start with 1 increment by 1\;
    driver-class-name: org.h2.Driver

  flyway:
    enabled: false

  output:
    ansi:
      enabled: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8880

logging:
  level:
    ROOT: info